#!/usr/bin/env bash
#
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

# delete symlink bin command
rm /usr/bin/clashcross

# delete desktop files
rm /usr/share/applications/com.clashcross.clashcross.desktop
update-desktop-database

echo "clashcross has successfully removed!"